USE DBMS_Lab3
GO


-- T1: T2 runs first
WAITFOR DELAY '00:00:10'
BEGIN TRAN
UPDATE Worker SET email = 'conflict1@mail.com' WHERE id = 3;
WAITFOR DELAY '00:00:10'
COMMIT TRAN

-- T2: Takes a snapshot of the row
SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN
SELECT * FROM Worker WHERE id = 3;
WAITFOR DELAY '00:00:10'
UPDATE Worker SET email = 'conflict2@mail.com' WHERE id = 3;
COMMIT TRAN


ALTER DATABASE DBMS_Lab3 SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE DBMS_Lab3 SET READ_COMMITTED_SNAPSHOT OFF;