-- Database setup
CREATE DATABASE IF NOT EXISTS documentsAndMovies;
USE documentsAndMovies;

CREATE TABLE IF NOT EXISTS Authors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    documentList VARCHAR(100) NOT NULL,
    movieList VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    contents VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    duration INT NOT NULL
);

SHOW TABLES;

DESCRIBE Authors;